Server/WebClientMVC/Controllers/SenderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebClientMVC.Models;
using WebClientMVC.SenderServiceReference1;
using System.Runtime.Serialization;
using System.Security.Cryptography;
using System.Text;

namespace WebClientMVC.Controllers
{
    public class SenderController : Controller
    {
        public readonly ISenderService _proxy;

        public SenderController(ISenderService proxy)
        {
            this._proxy = proxy;
        }

        // GET: Sender
        public ActionResult Index()
        {
            if (Request.Cookies.Get("login") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                string userName = Request.Cookies.Get("login").Values["feketePorzeczka"];
                LoginPassModel obj = new LoginPassModel { Username = userName };
                return RedirectToAction("LoggedInPost", obj);
            }
        }
        public ActionResult LoggedInPost(LoginPassModel user)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Index");
            var userFromDB = _proxy.GetAllUsers().SingleOrDefault(x => x.Username == user.Username);
            Models.SenderModel userToPass = new Models.SenderModel(userFromDB.Cpr, userFromDB.FirstName, userFromDB.LastName, userFromDB.PhoneNumber, userFromDB.Email, userFromDB.Address, userFromDB.ZipCode, userFromDB.City)
            {
                Username = userFromDB.Username,
                Password = userFromDB.Password,
                Points = userFromDB.Points,
                PassSalt=userFromDB.PassSalt,
                AccountType = userFromDB.AccountType
            };
            if (Request.Cookies.Get("login") != null)
            {
                if (userToPass.Password == Request.Cookies.Get("login").Values["pirosPorzeczka"])
                {
                    return View("LoggedIn", userToPass);
                }
                else return RedirectToAction("Index");
            }
            else return RedirectToAction("Index");
        }

        // GET: Sender/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Sender/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sender/Create
        [HttpPost]
        public ActionResult Create(RegisterModel reg)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View("Create", reg);
                SenderModel sender = new SenderModel(reg.Cpr, reg.FirstName, reg.LastName, reg.PhoneNumber, reg.Email, reg.Address + ", " + reg.Number, reg.ZipCode, reg.City) { AccountType = (int)AccountTypeEnum.SENDER, Password = reg.Password, Username = reg.Username, Points = 0 };
                var salt = Guid.NewGuid().ToString();
                int ret = _proxy.AddSender(new SenderResource { AccountType = sender.AccountType, Address = sender.Address, City = sender.City, Cpr = sender.Cpr, Email = sender.Email, FirstName = sender.FirstName, LastName = sender.LastName, Password = sender.Password, PassSalt = salt, PhoneNumber = sender.PhoneNumber, Points = sender.Points, Username = sender.Username, ZipCode = sender.ZipCode });
                switch (ret)
                {
                    case 1: return RedirectToAction("Index");
                    case 0: return View("Create", reg);
                    case -1:
                        {
                            ModelState.AddModelError("Cpr", "This CPR is already registered");
                            return View("Create", reg);
                        }
                    case -2:
                        {
                            ModelState.AddModelError("Email", "This email is already registered");
                            return View("Create", reg);
                        }
                    case -3:
                        {
                            ModelState.AddModelError("Username", "This username is taken");
                            return View("Create", reg);
                        }

                }
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        public ActionResult CreatePackage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreatePackage(Models.PackageModel package)
        {

            try
            {
                if (!ModelState.IsValid)
                    return View("CreatePackage", package);


                string username = Request.Cookies.Get("login").Values["feketePorzeczka"];

                var userPoints = _proxy.GetAllUsers().SingleOrDefault(x => x.Username == username).Points;

                if (int.Parse(package.Price) <= userPoints)
                {
                    var packageModelToInsert = new SenderServiceReference1.PackageModel { ToAddress = package.ToAddress, FromAddress = package.FromAddress, Weight = package.Weight, Width = package.Width, Height = package.Width, ReceiverFirstName = package.ReceiverFirstName, ReceiverLastName = package.ReceiverLastName, ReceiverPhoneNumber = package.ReceiverPhoneNumber };
                    var deliveryModelToInsert = new SenderServiceReference1.DeliveryModel { Distance = double.Parse(package.Distance.Split(' ')[0]), Price = int.Parse(package.Price) };

                    var result = _proxy.AddPackage(packageModelToInsert, username, deliveryModelToInsert);

                    if (result == 1)
                    {
                        return RedirectToAction("Index");
                    }

                    else return RedirectToAction("CreatePackage", package);
                }
                else
                {
                    ModelState.AddModelError("Price", "You do not have enough points!");
                    return View("CreatePackage", package);
                }
                
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }
        public ActionResult SentPackages(LoginPassModel user) {
            var userFromDB = _proxy.GetAllUsers().SingleOrDefault(x => x.Username == user.Username);
            var packages = _proxy.GetAllPackages().Where(x => x.SenderID == userFromDB.IDInDB).Select(x => new WebClientMVC.Models.PackageModel {
                Barcode = x.barcode,
                Distance = _proxy.GetDeliveryByPackageBarcode(x.barcode).Distance.ToString(),
                Price = _proxy.GetDeliveryByPackageBarcode(x.barcode).Price.ToString(),
                ReceiverFirstName = x.ReceiverFirstName,
                ReceiverLastName = x.ReceiverLastName,
                StatusID = x.StatusID
            });
            return View(packages);
        }
        // GET: Sender/Edit/5
        public ActionResult Edit(string Username)
        {
            var userFromDB = _proxy.GetAllUsers().SingleOrDefault(x => x.Username == Username);
            return View();
        }
        public ActionResult Logout()
        {
            try
            {
                HttpCookie cookie = new HttpCookie("login");
                cookie.Expires = DateTime.Now.AddDays(-1d);
                Response.Cookies.Add(cookie);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }
        // POST: Sender/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sender/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Sender/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Points()
        {
            return View();
        }

        public ActionResult Voucher()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Voucher(VoucherModel voucherm)
        {
            try
            {
                int status = 0;
                string username = Request.Cookies.Get("login").Values["feketePorzeczka"];
                var usedVouchers = _proxy.GetAllUsedVouchers();
                var voucher = _proxy.GetAllVouchers().Select(x => new VoucherModel { amount = x.amount, code = x.code }).SingleOrDefault(x => x.code == voucherm.code);
                if (voucher != null)
                {
                    foreach (var a in usedVouchers)
                    {
                        if (a.code == voucherm.code && a.username == username)
                        {
                            status = 1;
                        }
                    }
                    if (status == 0)
                    {
                        _proxy.UseVoucher(username, voucherm.code);
                    }
                    else
                    {
                        ModelState.AddModelError("code", "This voucher was already used.");
                        return View("Voucher", voucherm);
                    }
                }

Server/WebClientMVC/Views/Sender/Create.cshtml
@model WebClientMVC.Models.RegisterModel
@{
    ViewBag.Title = "Create";
}

<h2>Register</h2>

<script src="~/Scripts/autocomplete.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD-i9eQttqqwEOLH8tqPgYocn3Cx-aAa7I&signed_in=true&libraries=places&callback=initialize" async defer></script>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <div class="col-md-6">
            <h4>Personal information</h4>
            <hr />
            <div class="form-group">
                <label class="control-label col-md-2">CPR Number:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Cpr, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Cpr, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Firstname:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Lastname:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Phone number:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Email address:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control"} })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Address:</label>
                <div class="col-md-4">
                    <input class="form-control" id="autocomplete" onFocus="geolocate()" type="text" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Street, nr:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", id = "route", @readonly = "true" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-2">
                    @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control", id = "street_number", @readonly = "true" } })
                    @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Zip code:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control", @id= "postal_code", @readonly = "true" } })
                    @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">City:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", @id= "locality", @readonly = "true" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>
            <span id="administrative_area_level_1" style="display:none"></span>
            <span id="country" style="display:none"></span>
            <span id="street_number" style="display:none"></span>
        </div>
        <div class="col-md-6">
            <h4>Login information</h4>
            <hr />
            <div class="form-group">
                <label class="control-label col-md-2">Username:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Password:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>
            <div id="map"></div><br />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Server/WebClientMVC/Views/Sender/CreatePackage.cshtml
@model WebClientMVC.Models.PackageModel

@{
    ViewBag.Title = "Package";
}

<h2>Package delivery information</h2>
<script src="~/Scripts/packageMap.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD-i9eQttqqwEOLH8tqPgYocn3Cx-aAa7I&signed_in=true&libraries=places&callback=initialize" async defer></script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <p>Please fill in this form carefully. We are not responsible for mistaken information provided.</p>
        <hr />

        <div class="col-md-6">
            <h4>Receiver information</h4>
            <div class="form-group">
                <label class="control-label col-md-2">First name:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.ReceiverFirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReceiverFirstName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Last name:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.ReceiverLastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReceiverLastName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Phone number:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.ReceiverPhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReceiverPhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <h4>Package information</h4>
            <div class="form-group">
                <label class="control-label col-md-2">Width:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "form-control", placeholder = "cm" } })
                    @Html.ValidationMessageFor(model => model.Width, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Height:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control", placeholder = "cm" } })
                    @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Weight:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control", placeholder = "kg" } })
                    @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <h4>Order information</h4>
            <div class="form-group">
                <label class="control-label col-md-2">Price:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @id = "price", @readonly = "true" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <h4>Delivery addresses</h4>
            <p><span style="color:#e00000">IMPORTANT:</span> Please type in the address and be careful to include the street number also.</p>
            <div class="form-group">
                <label class="control-label col-md-2">Pick up:</label>
                <div class="col-md-4">
                    <input class="form-control" id="autocomplete" name="FromAddress" onFocus="geolocate()" type="text" />
                    @Html.ValidationMessageFor(model => model.FromAddress, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Destination:</label>
                <div class="col-md-4">
                    <input class="form-control" name="ToAddress" id="autocomplete2" type="text" />
                    @Html.ValidationMessageFor(model => model.ToAddress, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Distance:</label>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Distance, new { htmlAttributes = new { @class = "form-control", @id="distance", @readonly="true" } })
                    @Html.ValidationMessageFor(model => model.Distance, "", new { @class = "text-danger" })
                </div>
            </div>
            <div id="map"></div>
        </div>
        <span id="administrative_area_level_1" style="display:none"></span>
        <span id="country" style="display:none"></span>
        <span id="street_number" style="display:none"></span>
        <span id="route" style="display:none"></span>
        <span id="postal_code" style="display:none"></span>
        <span id="locality" style="display:none"></span>
        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <input type="submit" value="Send" class="btn btn-success" style="width:200px"/>
            </div>
        </div>
    </div>
}

Server/WebClientMVC/Views/Sender/Edit.cshtml
@model WebClientMVC.Models.SenderModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SenderModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cpr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cpr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cpr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Points, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Points, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Points, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Server/WebClientMVC/Views/Sender/Index.cshtml
@model WebClientMVC.Models.LoginModel
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal col-md-12">
    <h4>Sender</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">Username or email:</label>
        <div class="col-md-4">
            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Password:</label>
        <div class="col-md-4">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group col-md-7">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
    </div>
        <div class="col-md-7">
            @Html.ActionLink("Don't have an account? Register here", "Create")
        </div>

</div>
}

Server/WebClientMVC/Views/Sender/LoggedIn.cshtml
@model WebClientMVC.Models.SenderModel
@{
    ViewBag.Title = "Logged in";
}

<div class="col-md-12">
    <div class="col-md-3">
        <img style="border:2px solid #888888;border-radius:50%;height:40%;width:40%;background-color:white;" src="~/Resources/profile.png" />
        <h2 style="color:black;">@Model.FirstName @Model.LastName</h2><hr />
        <div id="options">
            <ul>
                <li><i class="material-icons" style="font-size:16px; position:relative;top:3px;">local_post_office</i>&nbsp;&nbsp;<a href="@Url.Action("SentPackages",new WebClientMVC.Models.LoginPassModel() { Username=Model.Username})">Sent packages</a></li>
                <li><i class="material-icons" style="font-size:16px; position:relative;top:3px;">money</i>&nbsp;&nbsp;<a href="@Url.Action("Points")">Point topup</a></li>
                <li style="display:none"><a href="@Url.Action("Edit", "Sender",new { Username = Model.Username })">Edit information</a></li>
                <li id="noborder"><i class="material-icons" style="font-size:16px; position:relative;top:3px;">logout</i>&nbsp;&nbsp;@Html.ActionLink("Log out", "Logout")</li>
            </ul>
        </div>
        
        <br />
        <br />
        <br />
    </div>
    <div class="col-md-9">

    </div>
</div>

Server/WebClientMVC/Views/Sender/Points.cshtml
@{
    ViewBag.Title = "Points";
}

<h2>Points</h2>
<div class="col-md-12">
    <hr />
    <div class="col-md-6">
        <center><img src="~/Resources/card.png" style="height:100px" /></center>
        <br />
        <center><p>Press this button if you would like to top up your points via your credit card</p></center>
        <center><a href="@Url.Action("Pay","Sender")" class="btn btn-default">Pay</a></center>
        <br />
    </div>
    <div class="col-md-6">
        <center><img src="~/Resources/voucher.png" style="height:100px" /></center>
        <br />
        <center><p>Do you have a voucher code? Press this button!</p></center>
        <center><a href="@Url.Action("Voucher","Sender")" class="btn btn-default">Voucher</a></center>
        <br />
    </div>
</div>